### ISSUE TITLE
`math:set`: Add math:set module

### ISSUE THREAD

**Issue by Ethanout** [xiaodou8593/math3.0_dslib#1]
1. Add basic operations: 
    - add
    - delete
    - intersection
    - union
    - complement
    - difference

2. Add property getter: 
    - get length

3. Add detector: 
    - detect if one or more elements are in the set
    - detect the basic operations‘ success count without the result of the set operations

**Comment by xiaodou8593** [comment]
命名问题：
    add -> _append
    delete -> _remove
    intersection -> _intersect
    union -> _union
    difference -> _differ

complement没必要，有差集就够了

风格问题：如果是能用记分板直接获取的attr，就不写getter

第一个detector建议写成接口函数 _elmof 和 _subof

第二个detector建议写成各种操作对应的返回值<res,int>

**Comment by Ethanout** [comment]
Since set is based on vanilla compound, the current functions are named `_new_key` and `_new_key_string`, should i change them to `_append` and `_append_string`?

**Comment by Ethanout** [comment]
```
#math:set/_new_key
# 在集合中插入新键(元素)，并返回这个新键(元素)是否已经存在
# 输入macro storage math:io {key}, storage math:io {key}
# 输出<res,int>

$execute store result score res int if data storage math:io set.$(key)
execute if score res int matches 1 run return 0
$data modify storage math:io set.$(key) set from storage math:io key
```
