### ISSUE TITLE
`math:compound`: add auto hash function

### ISSUE THREAD

**Issue by Ethanout** [xiaodou8593/math3.0_dslib#2]
Picking the right hash function to turn values into keys can be a pain. It'd be awesome if we could just have a "auto" hash for easy coding.

**Comment by Ethanout** [comment]
> Picking the right hash function to turn values into keys can be a pain. It'd be awesome if we could just have a "auto" hash for easy coding.

With this auto hash function, there's no need to worry about how the type of elements affects the keys—we can just focus on the "set" itself.

**Comment by xiaodou8593** [comment]
added
